name: simple_dart_checkbox
description: Simple Checkbox Component
version: 0.0.3
repository: https://github.com/simple-dart/checkbox
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.3
